controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
not_found:
    path: /{any}
    controller: App\Controller\Inicio::inicio
    requirements: